spring.application.name=mohaeng

# encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

# dbms connect 
# mysql connect  ---------------------------------------------
# RDS
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# jpa setting
# 실행 쿼리문 보이게 함
spring.jpa.show-sql=true     
 # 자동 ddl 구문 작동 안 되게 함
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=none   
spring.jpa.generate-ddl=true
# hibernate 가 생성하는 sql 문을 보기좋게 포탯팅할지 여부 지정
spring.jpa.properties.hibernate.format_sql=true
# jpa 가 연결할 db 종류 지정
spring.jpa.database=mysql
# hibernate 에 어떤 db 방언(dialect : db마다 sql문법, 함수, limit 처리 등)을 사용할지 지정
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.id.new_generator_mappings=false
spring.jpa.defer-datasource-initialization=true


# file upload limited file size
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# file upload and download folder setting
app.upload-dir=C:/upload_files

# 로그 출력 레벨 지정
logging.level.root=info
logging.level.org.hibernate=info

# json serializable error setting
spring.jackson.serialization.fail-on-empty-beans=false
#spring.jackson.property-naming-strategy=SNAKE_CASE
# 컬럼명 이름 표기법 지정 : 스프링은 기본 SNAKE_CASE 임, 
# 소문자만 사용하고 단어 사이에 '_' 를 사용하는 표기법을 말함 (예 : user_name)
# 사용 데이터베이스에 따라 대소문자 구분이 없는 경우에는 대소문자 모두 사용 가능함

# static access folder settings
spring.web.resources.static-locations=classpath:/static/,classpath:/resources/,classpath:/META-INF/resources/,file:src/main/webapp/resources/
spring.mvc.static-path-pattern=/**

# JWT
jwt.secret=${JWT_SECRET}
# access token:
jwt.access-exp=${JWT_ACCESS_EXP}
# refresh token: 
jwt.refresh-exp=${JWT_REFRESH_EXP}

# 소셜 계정 연동(OAuth2)
# 구글
spring.security.oauth2.client.registration.google.client-id=${OAUTH_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH_GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=${OAUTH_GOOGLE_SCOPE}

# Gmail SMTP 설정
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# SMTP 옵션
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 결제 API
toss.payments.client-key=${PAYMENTS_CLIENT_KEY}
toss.payments.secret-key=${PAYMENTS_SECRET_KEY}

# 문자 인증 API
solapi.api-key=${SOLAPI_API_KEY}
solapi.api-secret=${SOLAPI_API_SECRET}
solapi.from-number=${SOLAPI_FROM_NUMBER}

# 사업자 등록 번호 조회 API
nts.service-key=${NTS_SERVICE_KEY}

# s3
aws.region=${AWS_REGION}
aws.s3.bucket=${AWS_S3_BUCKET}
aws.access-key=${AWS_S3_ACCESS_KEY}
aws.secret-key=${AWS_S3_SECRET_KEY}

# TourAPI
tour.api.service-key=${TOUR_API_SERVICE_KEY}
tour.api.base-url=https://apis.data.go.kr/B551011/KorService2
tour.api.mobile-os=ETC
tour.api.mobile-app=MOHAENG
tour.api.arrange=A
tour.api.default-num-of-rows=30


# AI 프로젝트 연동
ai.base-url: ${AI_BASE_URL}
ai.api-key: ${AI_API_KEY}